# Warnings currently triggered by your code
- ignore: {name: "Redundant bracket"} # 3 hints
- ignore: {name: "Redundant if"} # 1 hint
- ignore: {name: "Use camelCase"} # 2 hints
- ignore: {name: "Use foldr"} # 1 hint
